import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import {
  Add,
  AddShoppingCart,
  Assessment,
  AspectRatio,
  Attachment,
  CallSplit,
  Category,
  CheckCircle,
  CloudDownload,
  CloudUpload,
  Contacts,
  Dashboard,
  DataUsage,
  Description,
  Email,
  EventNote,
  FormatListNumberedRtl,
  GroupAdd,
  Home,
  Input,
  ListAlt,
  LocalLibrary,
  LocalPrintshop,
  LocationOn,
  NoteAdd,
  People,
  PlaylistAdd,
  PlusOne,
  PostAdd,
  RemoveCircle,
  Reorder,
  Save,
  Settings,
  ShoppingCart,
  Storage,
  Store,
  Storefront,
  TextFields,
  TextRotationNone,
  Tune,
  Cached,
  Clear,
  PhotoCamera,
  LocalShipping,
  FeaturedPlayList,
  LocalOffer,
  Assignment,
  Timeline,
  FormatListNumbered,
  Warning,
  Receipt,
  Inbox,
  AccountBox,
  NotificationsActive,
  EditLocation,
  MenuBook,
  Print,
  Business,
  SubdirectoryArrowLeft,
  SubdirectoryArrowRight,
  ImportExport,
  SettingsBackupRestore,
  AssignmentInd,
  AccountCircle,
  Security,
} from "@material-ui/icons";
import { BiDetail, BiRefresh, BiBarcodeReader, BiPackage, BiRuler } from "react-icons/bi"
import { IoFileTrayStackedSharp } from "react-icons/io5"
import { RiFileTransferFill } from "react-icons/ri"
import { AiOutlineNumber } from "react-icons/ai"
import { GiReturnArrow } from "react-icons/gi"
import { ImMoveDown } from "react-icons/im"
import { BsExclamationOctagonFill } from "react-icons/bs"
import { FaBox, FaFileInvoice, FaTruckLoading, FaThList, FaWarehouse } from "react-icons/fa"
// import { HiRectangleGroup } from "react-icons/hi"

import { CenteralUIColor } from "./CustomStyle";

const buttonComponents = {
  "All Reports": Assessment,
  Add: Add,
  "Adjust Stocks": Tune,
  Activate: CheckCircle,
  Adjust: Cached,
  "Inventory Adjustment": PlusOne,
  Areas: AspectRatio,
  Attachment: Attachment,
  "Basic Settings": Settings,
  "Base Settings": Tune,
  "Box Creation": Inbox,
  Carriers: LocalShipping,
  Categories: Category,
  Clear: Clear,
  "Company Info": Business,
  Concessions: Storefront,
  Config: Settings,
  "Critical Stock": Warning,
  "Current Stock": LocalLibrary,
  "User Fields": TextFields,
  // "Location Groups": AiOutlineGroup,
  "PO UField": TextFields,
  "SO UField": TextFields,
  "Product UField": TextFields,
  "Product": FaBox,
  "Returns UField": TextFields,
  "Receive Transfer UField": TextFields,
  "Role Info": Security,
  User: AccountBox,
  "User Accounts": AccountCircle,
  Home: Home,
  Logs: AssignmentInd,
  "Audit Trail": AssignmentInd,
  Storage: Storage,
  Data: DataUsage,
  Sales: ShoppingCart,
  Dashboard: Dashboard,
  "Document No.": AiOutlineNumber,
  "New Sales Quote": PostAdd,
  "New Sales Order": AddShoppingCart,
  "Sales Order List": ListAlt,
  "New Customer": GroupAdd,
  "New Purchase Order": NoteAdd,
  "Purchase Order List": ListAlt,
  Vendor: GroupAdd,
  "Vendor List": ListAlt,
  "New Product": PlaylistAdd,
  "Product Categories": Category,
  "Transfer Stock": CallSplit,
  "Reorder Stock": Reorder,
  "Work Order": EventNote,
  "Print Setup": LocalPrintshop,
  "Location Settings": LocationOn,
  References: Contacts,
  "Doc. Numbers": Description,
  "Rename Fields": TextRotationNone,
  "Email settings": Email,
  Supply : Add,
  Save: Save,
  Remove: RemoveCircle,
  Photo: PhotoCamera,
  Warehouses: FaWarehouse,
  Zones: Storage,
  "Location Groups": IoFileTrayStackedSharp,
  Locations: LocationOn,
  Owners: People,
  Vendors: Store,
  "Product List": FeaturedPlayList,
  "Unit of Measures": Assessment,
  "Product Pricing": LocalOffer,
  "Purchase Order": ShoppingCart,
  "Goods Receiving": Input,
  "Put Away": Assignment,
  "Inventory List": ListAlt,
  "Running Balance": FormatListNumberedRtl,
  "Stock Movement": Timeline,
  "Relocate Stocks": EditLocation,
  "Inventory Count": FormatListNumbered,
  "Shipment Orders": AddShoppingCart,
  "Order Picking": Assignment,
  "Delivery Receipts": Receipt,
  Loading: LocalShipping,
  "Notifications": NotificationsActive,
  Import: CloudUpload,
  Export: CloudDownload,
  Transaction: MenuBook,
  Reports: Print,
  Warehouse: Store,
  "Warehouse Info": Store,
  Organizations: Business,
  Inbound: SubdirectoryArrowRight,
  Outbound: SubdirectoryArrowLeft,
  Inventory: Storage,
  Setup: Settings,
  "Data Migration": ImportExport,
  Log: MenuBook,
  Rotation: BiRefresh,
  "LOT Details": BiDetail,
  Replenishment: SettingsBackupRestore,
  Tasks: AssignmentInd,
  "Receive Transfer": RiFileTransferFill,
  "Receive Returns": GiReturnArrow,
  "Inventory Move": ImMoveDown,
  "Critical Stocks": BsExclamationOctagonFill,
  "Tagged Items": BiBarcodeReader,
  "Shipment Order": FaFileInvoice,
  "Packing": BiPackage,
  Shipment: FaTruckLoading,
  "UOM Ref": BiRuler,
  "Product Conditions": FaThList
};

const useStyles = makeStyles((theme) => ({
  icon: {
    color: CenteralUIColor.IconColor,
  },
}));

function IconBuilder(props) {
  const classes = useStyles();
  const TagName = buttonComponents[props.tag];

  return <TagName className={classes.icon} size="20px" />;
}

export default IconBuilder;
