/* MENU or User Allowed Modules */
export const GET_MENU = "GET_MENU";
export const CREATE_MENU = "CREATE_MENU";
export const UPDATE_MENU = "UPDATE_MENU";

// ACTIVE MODULES
export const SET_ACTIVE_MODULES = "SET_ACTIVE_MODULES";
export const REMOVE_FROM_ACTIVE_MODULES = "REMOVE_FROM_ACTIVE_MODULES";
export const SET_ACTIVE_MODULE_DATA = "SET_ACTIVE_MODULE_DATA";
export const GET_ACTIVE_MODULE_DATA = "GET_ACTIVE_MODULE_DATA";
export const REMOVE_ACTIVE_MODULE_DATA = "REMOVE_ACTIVE_MODULE_DATA";
export const SET_NEW_SEQUENCE_ACTIVE_MODULES = "SET_NEW_SEQUENCE_ACTIVE_MODULES";
export const SET_SELECTED_MODULE_LINK = "SET_SELECTED_MODULE_LINK"

// ZONES
export const SAVE_ZONE_DETAILS = "SAVE_ZONE_DETAILS";
export const ZONE_SELECTED_ROW = "ZONE_SELECTED_ROW";

/* SYSTEM ROLES or User Groups */
export const GET_ROLES = "GET_ROLES";
export const CREATE_ROLES = "CREATE_ROLES";
export const UPDATE_ROLES = "UPDATE_ROLES";
export const DELETE_ROLES = "DELETE_ROLES";
export const SELECT_ALL_ACTIONS_ROLES = "SELECT_ALL_ACTIONS_ROLES"

export const GET_ROLE_DETAILS = "GET_ROLE_DETAILS";
export const CREATE_ROLE_DETAILS = "CREATE_ROLE_DETAILS";
export const UPDATE_ROLE_DETAILS = "UPDATE_ROLE_DETAILS";
export const DELETE_ROLE_DETAILS = "DELETE_ROLE_DETAILS";

/* USER ACCOUNTS */
export const GET_USERACC = "GET_USERACC";
export const CREATE_USERACC = "CREATE_USERACC";
export const UPDATE_USERACC = "UPDATE_USERACC";
export const DELETE_USERACC = "DELETE_USERACC";


/* SYSTEM MODULES */
export const GET_SYSMODULE = "GET_SYSMODULE";
export const CREATE_SYSMODULE = "CREATE_SYSMODULE";
export const UPDATE_SYSMODULE = "UPDATE_SYSMODULE";
export const DELETE_SYSMODULE = "DELETE_SYSMODULE";

/* SYSTEM ACTIONS */
export const GET_SYSACTION = "GET_SYSACTION";
export const CREATE_SYSACTION = "CREATE_SYSACTION";
export const UPDATE_SYSACTION = "UPDATE_SYSACTION";
export const DELETE_SYSACTION = "DELETE_SYSACTION";

/* SYSTEM ACCESS */
export const GET_SYSACCESS = "GET_SYSACCESS";
export const CREATE_SYSACCESS = "CREATE_SYSACCESS";
export const UPDATE_SYSACCESS = "UPDATE_SYSACCESS";
export const DELETE_SYSACCESS = "DELETE_SYSACCESS";

/* LOCATION */
export const GET_LOCATION = "GET_LOCATION";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_LOCATION_DATA =  "SET_LOCATION_DATA";

/* READER */
export const GET_READER = "GET_READER";
export const CREATE_READER = "CREATE_READER";
export const UPDATE_READER = "UPDATE_READER";
export const DELETE_READER = "DELETE_READER";

/* READER ANTENNA */
export const GET_READER_ANTENNA = "GET_READER_ANTENNA";
export const CREATE_READER_ANTENNA = "CREATE_READER_ANTENNA";
export const UPDATE_READER_ANTENNA = "UPDATE_READER_ANTENNA";
export const DELETE_READER_ANTENNA = "DELETE_READER_ANTENNA";

/* COMPANY INFORMATION */
export const GET_COMPANY_INFO = "GET_COMPANY_INFO";
export const CREATE_COMPANY_INFO = "CREATE_COMPANY_INFO";
export const UPDATE_COMPANY_INFO = "UPDATE_COMPANY_INFO";
export const DELETE_COMPANY_INFO = "DELETE_COMPANY_INFO";

/* COUNTRY REF INFORMATION  */
export const GET_COUNTRY_REF = "GET_COUNTRY_REF";
export const CREATE_COUNTRY_REF = "CREATE_COUNTRY_REF";
export const UPDATE_COUNTRY_REF = "UPDATE_COUNTRY_REF";
export const DELETE_COUNTRY_REF = "DELETE_COUNTRY_REF";

/* RECEIVING_ADDRESS REF INFORMATION  */
export const GET_RECEIVING_ADDRESS_REF = "GET_RECEIVING_ADDRESS_REF";
export const CREATE_RECEIVING_ADDRESS_REF = "CREATE_RECEIVING_ADDRESS_REF";
export const UPDATE_RECEIVING_ADDRESS_REF = "UPDATE_RECEIVING_ADDRESS_REF";
export const DELETE_RECEIVING_ADDRESS_REF = "DELETE_RECEIVING_ADDRESS_REF";

/* ADDRESS TYPE REF INFORMATION  */
export const GET_ADDRESS_TYPE_REF = "GET_ADDRESS_TYPE_REF";
export const CREATE_ADDRESS_TYPE_REF = "CREATE_ADDRESS_TYPE_REF";
export const UPDATE_ADDRESS_TYPE_REF = "UPDATE_ADDRESS_TYPE_REF";
export const DELETE_ADDRESS_TYPE_REF = "DELETE_ADDRESS_TYPE_REF";

/* CARRIERS REF INFORMATION  */
export const GET_CARRIERS_REF = "GET_CARRIERS_REF";
export const CREATE_CARRIERS_REF = "CREATE_CARRIERS_REF";
export const UPDATE_CARRIERS_REF = "UPDATE_CARRIERS_REF";
export const DELETE_CARRIERS_REF = "DELETE_CARRIERS_REF";

/* PAYMENT METHOD REF INFORMATION  */
export const GET_PAYMENT_METHOD_REF = "GET_PAYMENT_METHOD_REF";
export const CREATE_PAYMENT_METHOD_REF = "CREATE_PAYMENT_METHOD_REF";
export const UPDATE_PAYMENT_METHOD_REF = "UPDATE_PAYMENT_METHOD_REF";
export const DELETE_PAYMENT_METHOD_REF = "DELETE_PAYMENT_METHOD_REF";

/* PAYMENT METHOD REF INFORMATION  */
export const GET_PAYMENT_TERMS_REF = "GET_PAYMENT_TERMS_REF";
export const CREATE_PAYMENT_TERMS_REF = "CREATE_PAYMENT_TERMS_REF";
export const UPDATE_PAYMENT_TERMS_REF = "UPDATE_PAYMENT_TERMS_REF";
export const DELETE_PAYMENT_TERMS_REF = "DELETE_PAYMENT_TERMS_REF";

/* UNITS REF INFORMATION  */
export const GET_UNITS_REF = "GET_UNITS_REF";
export const CREATE_UNITS_REF = "CREATE_UNITS_REF";
export const UPDATE_UNITS_REF = "UPDATE_UNITS_REF";
export const DELETE_UNITS_REF = "DELETE_UNITS_REF";

/* SALES REP REF INFORMATION  */
export const GET_SALES_REP_REF = "GET_SALES_REP_REF";
export const CREATE_SALES_REP_REF = "CREATE_SALES_REP_REF";
export const UPDATE_SALES_REP_REF = "UPDATE_SALES_REP_REF";
export const DELETE_SALES_REP_REF = "DELETE_SALES_REP_REF";

/* CURRENCY INFORMATION  */
export const GET_CURRENCY = "GET_CURRENCY";
export const CREATE_CURRENCY = "CREATE_CURRENCY";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";


/* CURRENCY CONVERSION INFORMATION  */
export const GET_CURRENCY_CONVERSION = "GET_CURRENCY_CONVERSION";
export const CREATE_CURRENCY_CONVERSION = "CREATE_CURRENCY_CONVERSION";
export const UPDATE_CURRENCY_CONVERSION = "UPDATE_CURRENCY_CONVERSION";
export const DELETE_CURRENCY_CONVERSION = "DELETE_CURRENCY_CONVERSION";


/* COSTING METHOD INFORMATION  */
export const GET_COSTING_METHOD = "GET_COSTING_METHOD";
export const CREATE_COSTING_METHOD = "CREATE_COSTING_METHOD";
export const UPDATE_COSTING_METHOD = "UPDATE_COSTING_METHOD";
export const DELETE_COSTING_METHOD = "DELETE_COSTING_METHOD";


/* PRICING SCHEME INFORMATION  */
export const GET_PRICING_SCHEME = "GET_PRICING_SCHEME";
export const CREATE_PRICING_SCHEME = "CREATE_PRICING_SCHEME";
export const UPDATE_PRICING_SCHEME = "UPDATE_PRICING_SCHEME";
export const DELETE_PRICING_SCHEME = "DELETE_PRICING_SCHEME";


/* TAX CODE INFORMATION  */
export const GET_TAX_CODE = "GET_TAX_CODE";
export const CREATE_TAX_CODE = "CREATE_TAX_CODE";
export const UPDATE_TAX_CODE = "UPDATE_TAX_CODE";
export const DELETE_TAX_CODE = "DELETE_TAX_CODE";

/* TAX SCHEME INFORMATION  */
export const GET_TAX_SCHEME = "GET_TAX_SCHEME";
export const CREATE_TAX_SCHEME = "CREATE_TAX_SCHEME";
export const UPDATE_TAX_SCHEME = "UPDATE_TAX_SCHEME";
export const DELETE_TAX_SCHEME = "DELETE_TAX_SCHEME";


/* SYS GLOBAL COMPANY PREFERENCES  */
export const GET_COMPANY_PREFRENCES = "GET_COMPANY_PREFRENCES";
export const CREATE_COMPANY_PREFRENCES = "CREATE_COMPANY_PREFRENCES";
export const UPDATE_COMPANY_PREFRENCES = "UPDATE_COMPANY_PREFRENCES";
export const DELETE_COMPANY_PREFRENCES = "DELETE_COMPANY_PREFRENCES";

/* SYS GLOBAL DOC NO FORMAT  */
export const GET_DOC_NO_FORMAT = "GET_DOC_NO_FORMAT";
export const CREATE_DOC_NO_FORMAT = "CREATE_DOC_NO_FORMAT";
export const UPDATE_DOC_NO_FORMAT = "UPDATE_DOC_NO_FORMAT";
export const DELETE_DOC_NO_FORMAT = "DELETE_DOC_NO_FORMAT";
export const SET_DOC_NO_FORMAT_DATA = "SET_DOC_NO_FORMAT_DATA";
export const SET_DOC_NO_FORMAT_SELECTED_ROW = "SET_DOC_NO_FORMAT_SELECTED_ROW";
export const SET_SETTING_CURRENT_TAB = "SET_SETTING_CURRENT_TAB";

/* SYS GLOBAL CUSTOM FIELD */
export const GET_CUSTOM_FIELDS = "GET_CUSTOM_FIELDS";
export const CREATE_CUSTOM_FIELDS = "CREATE_CUSTOM_FIELDS";
export const UPDATE_CUSTOM_FIELDS = "UPDATE_CUSTOM_FIELDS";
export const DELETE_CUSTOM_FIELDS = "DELETE_CUSTOM_FIELDS";

/* T CATEGORY */
export const GET_CATEGORY = "GET_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

/* T PRODUCT */
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT";
export const CREATE_CATEGORY_PRODUCT = "CREATE_CATEGORY_PRODUCT";
export const UPDATE_CATEGORY_PRODUCT = "UPDATE_CATEGORY_PRODUCT";
export const DELETE_CATEGORY_PRODUCT = "DELETE_CATEGORY_PRODUCT";

/* T PIN */
export const GET_PIN = "GET_PIN";
export const CREATE_PIN = "CREATE_PIN";
export const UPDATE_PIN = "UPDATE_PIN";
export const DELETE_PIN = "DELETE_PIN";

/* T PRODUCT */
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";

/* PRODUCT PRICING */
export const GET_PRICE_ADJUSTMENT = "GET_PRICE_ADJUSTMENT";
export const CREATE_PRICE_ADJUSTMENT = "CREATE_PRICE_ADJUSTMENT";
export const UPDATE_PRICE_ADJUSTMENT = "UPDATE_PRICE_ADJUSTMENT";
export const DELETE_PRICE_ADJUSTMENT = "DELETE_PRICE_ADJUSTMENT";

export const GET_PRICE_ADJUSTMENT_LINE = "GET_PRICE_ADJUSTMENT_LINE";
export const CREATE_PRICE_ADJUSTMENT_LINE = "CREATE_PRICE_ADJUSTMENT_LINE";
export const UPDATE_PRICE_ADJUSTMENT_LINE = "UPDATE_PRICE_ADJUSTMENT_LINE";
export const DELETE_PRICE_ADJUSTMENT_LINE = "DELETE_PRICE_ADJUSTMENT_LINE";

export const GET_CACHE_SUMMARY_COST = "GET_CACHE_SUMMARY_COST";
export const CREATE_CACHE_SUMMARY_COST = "CREATE_CACHE_SUMMARY_COST";
export const UPDATE_CACHE_SUMMARY_COST = "UPDATE_CACHE_SUMMARY_COST";
export const DELETE_CACHE_SUMMARY_COST = "DELETE_CACHE_SUMMARY_COST";


export const GET_ITEM_PRICE = "GET_ITEM_PRICE";
export const CREATE_ITEM_PRICE = "CREATE_ITEM_PRICE";
export const UPDATE_ITEM_PRICE = "UPDATE_ITEM_PRICE";
export const DELETE_ITEM_PRICE = "DELETE_ITEM_PRICE";

/* PRODUCT STOCK ADJUSTMENT */
export const GET_STOCK_ADJUSTMENT = "GET_STOCK_ADJUSTMENT";
export const CREATE_STOCK_ADJUSTMENT = "CREATE_STOCK_ADJUSTMENT";
export const UPDATE_STOCK_ADJUSTMENT = "UPDATE_STOCK_ADJUSTMENT";
export const DELETE_STOCK_ADJUSTMENT = "DELETE_STOCK_ADJUSTMENT";

/* PRODUCT STOCK ADJUSTMENT LINE */
export const GET_STOCK_ADJUSTMENT_LINE = "GET_STOCK_ADJUSTMENT_LINE";
export const CREATE_STOCK_ADJUSTMENT_LINE = "CREATE_STOCK_ADJUSTMENT_LINE";
export const UPDATE_STOCK_ADJUSTMENT_LINE = "UPDATE_STOCK_ADJUSTMENT_LINE";
export const DELETE_STOCK_ADJUSTMENT_LINE = "DELETE_STOCK_ADJUSTMENT_LINE";


/* PRODUCT ACC BALANCE & CHECKPOINT */
export const GET_PROD_ACC_BALANCE = "GET_PROD_ACC_BALANCE";
export const CREATE_PROD_ACC_BALANCE = "CREATE_PROD_ACC_BALANCE";
export const UPDATE_PROD_ACC_BALANCE = "UPDATE_PROD_ACC_BALANCE";
export const DELETE_PROD_ACC_BALANCE = "DELETE_PROD_ACC_BALANCE";

/* FILE ATTACHMENT */
export const GET_FILE_ATTACHMENT = "GET_FILE_ATTACHMENT";
export const CREATE_FILE_ATTACHMENT = "CREATE_FILE_ATTACHMENT";
export const UPDATE_FILE_ATTACHMENT = "UPDATE_FILE_ATTACHMENT";
export const DELETE_FILE_ATTACHMENT = "DELETE_FILE_ATTACHMENT";
export const CLEAR_FILE_ATTACHMENT = "CLEAR_FILE_ATTACHMENT";

/* PRODUCT ATTACHMENT */
export const GET_PRODUCT_ATTACHMENT = "GET_PRODUCT_ATTACHMENT";
export const CREATE_PRODUCT_ATTACHMENT = "CREATE_PRODUCT_ATTACHMENT";
export const UPDATE_PRODUCT_ATTACHMENT = "UPDATE_PRODUCT_ATTACHMENT";
export const DELETE_PRODUCT_ATTACHMENT = "DELETE_PRODUCT_ATTACHMENT";


/* VENDOR */
export const GET_VENDOR = "GET_VENDOR";
export const CREATE_VENDOR = "CREATE_VENDOR";
export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";


/* VENDOR ADDRESS */
export const GET_VENDOR_ADDRESS = "GET_VENDOR_ADDRESS";
export const CREATE_VENDOR_ADDRESS = "CREATE_VENDOR_ADDRESS";
export const UPDATE_VENDOR_ADDRESS = "UPDATE_VENDOR_ADDRESS";
export const DELETE_VENDOR_ADDRESS = "DELETE_VENDOR_ADDRESS";

// PO
export const ADD_PO_ORDER = "ADD_PO_ORDER"




